Replace the deprecated gtk_widget_set_state with gtk_widget_set_state…
mate-desktop/mate-control-center pull request #652
Opened 2021-07-24 08:38 UTC by zhuyaliang

Replace the deprecated gtk_widget_set_state with gtk_widget_set_state_flags

2021-07-26 20:52 UTC, raveit65 approved these changes
LGTM

2021-07-28 15:57 UTC, vkareh requested changes

2021-07-28 15:57 UTC, vkareh commented on libslab/app-shell.c
> +			gtk_widget_set_state_flags (GTK_WIDGET (data->group_launcher), GTK_STATE_NORMAL, FALSE);
`GTK_STATE_NORMAL` should be `GTK_STATE_FLAG_NORMAL`

2021-07-28 15:57 UTC, vkareh commented on libslab/app-shell.c
> +		gtk_widget_set_state_flags (GTK_WIDGET (launcher), GTK_STATE_NORMAL, FALSE);
`GTK_STATE_NORMAL` should be `GTK_STATE_FLAG_NORMAL`

2021-07-28 16:11 UTC, vkareh approved these changes
LGTM

2021-07-28 16:11 UTC, merged